name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 5.2.1
repository: https://github.com/tlserver/flutter_map_location_marker
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass:
    git:
      url: https://github.com/hemanthrajv/flutter_compass.git
      ref: 8f753aefe76b08092c0e5bda93775ade8fe66016
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
